description: 'tty: tty_buffer: Fix the softlockup issue in flush_to_ldisc'
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-47185
- https://git.kernel.org/stable/c/0380f643f3a7a61b0845cdc738959c2ad5735d61
- https://git.kernel.org/stable/c/b1ffc16ec05ae40d82b6e373322d62e9d6b54fbc
- https://git.kernel.org/stable/c/4c1623651a0936ee197859824cdae6ebbd04d3ed
- https://git.kernel.org/stable/c/4f300f47dbcf9c3d4b2ea76c8554c8f360400725
- https://git.kernel.org/stable/c/d491c84df5c469dd9621863b6a770b3428137063
- https://git.kernel.org/stable/c/77e9fed33056f2a88eba9dd4d2d5412f0c7d1f41
- https://git.kernel.org/stable/c/5c34486f04700f1ba04907231dce0cc2705c2d7d
- https://git.kernel.org/stable/c/3968ddcf05fb4b9409cd1859feb06a5b0550a1c1
- https://lore.kernel.org/linux-cve-announce/2024041033-CVE-2021-47185-c363@gregkh/
comments:
  cip/cip-kernel-sec: Introduced commit is not determined.Fixed in v5.16-rc1.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [4f300f47dbcf9c3d4b2ea76c8554c8f360400725]
  cip/4.19-rt: [4f300f47dbcf9c3d4b2ea76c8554c8f360400725]
  cip/4.4: [0380f643f3a7a61b0845cdc738959c2ad5735d61]
  cip/4.4-rt: [0380f643f3a7a61b0845cdc738959c2ad5735d61]
  cip/4.4-st: [0380f643f3a7a61b0845cdc738959c2ad5735d61]
  cip/5.10: [77e9fed33056f2a88eba9dd4d2d5412f0c7d1f41]
  cip/5.10-rt: [77e9fed33056f2a88eba9dd4d2d5412f0c7d1f41]
  debian/buster-security: ['version:debian/4.19.232-1']
  mainline: [3968ddcf05fb4b9409cd1859feb06a5b0550a1c1]
  stable/4.19: [4f300f47dbcf9c3d4b2ea76c8554c8f360400725]
  stable/4.4: [0380f643f3a7a61b0845cdc738959c2ad5735d61]
  stable/5.10: [77e9fed33056f2a88eba9dd4d2d5412f0c7d1f41]
  stable/5.15: [5c34486f04700f1ba04907231dce0cc2705c2d7d]
  stable/5.4: [d491c84df5c469dd9621863b6a770b3428137063]
  ubuntu/bionic: [a767c71908c5de31073adc0505a87a21e24ce34a]
  ubuntu/focal: [ca19a3955fdc67876b2070ae2fe48c70a6c170fb]
