description: |-
  There is a logic error in io_uring's implementation which can be used to
  trigger a use-after-free vulnerability leading to privilege escalation. In
  the io_prep_async_work function the assumption that the last
  io_grab_identity call cannot return false is not true, and in this case the
  function will use the init_cred or the previous linked requests identity to
  do operations instead of using the current identity. This can lead to
  reference counting issues causing use-after-free. We recommend upgrading
  past version 5.10.161.
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-0240
- https://kernel.dance/#788d0824269bef539fe31a785b1517882eafed93
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/io_uring?h=linux-5.10.y&id=788d0824269bef539fe31a785b1517882eafed93
- https://github.com/gregkh/linux/commit/1e6fa5216a0e59ef02e8b6b40d553238a3b81d49
- https://lore.kernel.org/stable/5ad43b3a-c1a9-b830-c58a-163864fd07bc@kernel.dk/
comments:
  debian/carnil: |-
    Introduced with 1e6fa5216a0e ("io_uring: COW io_identity on
    mismatch") in 5.10-rc1. For mainline and other branches
    consider the commit removing io_identity as the final one
    fixing the issue.
  ubuntu/sbeattie: |-
    no fixes information given, so using 2b188cc1bb85 ("Add
      io_uring IO interface") as an upper bounds on affected versions; this
      is almost surely incorrect.
introduced-by:
  mainline: [1e6fa5216a0e59ef02e8b6b40d553238a3b81d49]
fixed-by:
  mainline: [4379bf8bd70b5de6bba7d53015b0c36c57a634ee]
  stable/5.10: [788d0824269bef539fe31a785b1517882eafed93]
  ubuntu/focal: ['version:5.4.0-9.12']
ignore:
  cip/4.19: Not affected
  cip/4.19-rt: Not affected
  cip/4.4: Not affected
  cip/4.4-rt: Not affected
  cip/4.4-st: Not affected
  stable/4.14: Not affected
  stable/4.19: Not affected
  stable/5.4: Not affected
