description: 'can: usb_8dev: usb_8dev_start_xmit(): fix double dev_kfree_skb() in
  error path'
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28388
- https://git.kernel.org/linus/3d3925ff6433f98992685a9679613a2cc97f3ce2
- https://github.com/torvalds/linux/commit/3d3925ff6433f98992685a9679613a2cc97f3ce2
- https://ubuntu.com/security/notices/USN-5416-1
- https://ubuntu.com/security/notices/USN-5469-1
- https://ubuntu.com/security/notices/USN-5493-1
- https://ubuntu.com/security/notices/USN-5493-2
- https://ubuntu.com/security/notices/USN-5505-1
- https://ubuntu.com/security/notices/USN-5513-1
comments:
  debian/bwh: The fix says this bug was present since the driver was added in 3.9.
  debian/carnil: |-
    For 5.16.y fixed as well in 5.16.19 and for 5.17.y fixed in
    5.17.2.
  masami: |-
    Introduced by 0024d8a ("can: usb_8dev: Add support for USB2CAN interface
    from 8 devices") that was merged in 3.9-rc1.
introduced-by:
  mainline: [0024d8ad1639e32d717445c69ca813fd19c2a91c]
fixed-by:
  cip/4.19: [8eb78da898079c0d7250c32ebf0c35fb81737abe]
  cip/4.19-rt: [8eb78da898079c0d7250c32ebf0c35fb81737abe]
  cip/5.10: [5318cdf4fd834856ce71238b064f35386f9ef528]
  debian/buster-security: ['version:debian/4.19.249-1']
  mainline: [3d3925ff6433f98992685a9679613a2cc97f3ce2]
  stable/4.14: [a5e2259173eb52a728bbf32e02aa9a388451e614]
  stable/4.19: [8eb78da898079c0d7250c32ebf0c35fb81737abe]
  stable/5.10: [5318cdf4fd834856ce71238b064f35386f9ef528]
  stable/5.15: [f2ce5238904f539648aaf56c5ee49e5eaf44d8fc]
  stable/5.16: [3e006cf0fb809815d56e59c9de4486fbe253ccdf]
  stable/5.17: [29d6c06168faa23ce23db3321981c8fde576c95c]
  stable/5.4: [660784e7194ac2953aebe874c1f75f2441ba3d19]
  ubuntu/bionic: [987b04e24687fd82ff3ca196b30bdf3b3d834639]
  ubuntu/focal: [2fc40823c6607f1798e02739ca779922c92dd026]
ignore:
  debian/stretch-security: EOL
