description: |-
  An issue was discovered in the Linux kernel before 5.8.2. fs/io_uring.c has
  a use-after-free related to io_async_task_func and ctx reference holding,
  aka CID-6d816e088c35.
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36387
- https://git.kernel.org/linus/6d816e088c359866f9867057e04f244c608c42fe
- https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.2
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6d816e088c359866f9867057e04f244c608c42fe
- https://sites.google.com/view/syzscope/kasan-use-after-free-read-in-io_async_task_func
- https://syzkaller.appspot.com/bug?id=ce5f07d6ec3b5050b8f0728a3b389aa510f2591b
- https://www.cve.org/CVERecord?id=CVE-2020-36387
comments:
  masami: |-
    This CVE affects before Linux 5.8.2. However io_uring was introduced at
    Linux 5.1 so that CIP kernels aren't affected this vulnerability.
introduced-by:
  mainline: [b41e98524e424d104aa7851d54fd65820759875a]
fixed-by:
  mainline: [6d816e088c359866f9867057e04f244c608c42fe]
  ubuntu/focal: ['version:5.4.0-9.12']
  ubuntu/groovy: ['version:5.8.0-18.19']
ignore:
  cip/linux-4.19: io_uring feature does not exist
  cip/linux-4.19-rt: io_uring feature does not exist
  cip/linux-4.4: io_uring feature does not exist
  cip/linux-4.4-rt: io_uring feature does not exist
  cip/linux-5.10: Does not affect linux-5.10
  cip/linux-5.10-rt: Does not affect linux-5.10
