description: 'f2fs: fix to do sanity check on last xattr entry in __f2fs_setxattr()'
references:
- https://bugzilla.kernel.org/show_bug.cgi?id=215235
- https://git.kernel.org/pub/scm/linux/kernel/git/chao/linux.git/commit/?h=dev&id=5598b24efaf4892741c798b425d543e4bed357a1
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45469
- https://ubuntu.com/security/notices/USN-5343-1
- https://ubuntu.com/security/notices/USN-5377-1
- https://www.cve.org/CVERecord?id=CVE-2021-45469
comments:
  debian/bwh: This is due to an incomplete fix for CVE-2019-9453.
  debian/carnil: for 5.15.y fixed as well in 5.15.12.
  masami: |-
    OOB access bug in  __f2fs_setxattr().
    Although it fixed in stable tree, it isn't fixed in mainline yet at 2021/12/30 (it fixed in
    https://git.kernel.org/pub/scm/linux/kernel/git/chao/linux.git/commit/?h=dev&id=5598b24efaf4892741c798b425d543e4bed357a1).
reporters:
- Wenqing Liu
introduced-by:
  mainline: [af48b85b8cd3fbb12c9b6759c16db6d69c0b03da]
fixed-by:
  cip/4.19: [f9dfa44be0fb5e8426183a70f69a246cf5827f49]
  cip/4.19-rt: [f9dfa44be0fb5e8426183a70f69a246cf5827f49]
  cip/5.10: [fffb6581a23add416239dfcf7e7f3980c6b913da]
  cip/5.10-rt: [fffb6581a23add416239dfcf7e7f3980c6b913da]
  debian/buster-security: ['version:debian/4.19.232-1']
  mainline: [645a3c40ca3d40cc32b4b5972bf2620f2eb5dba6]
  stable/4.14: [88dedecc24763c2e0bc1e8eeb35f9f2cd785a7e5]
  stable/4.19: [f9dfa44be0fb5e8426183a70f69a246cf5827f49]
  stable/5.10: [fffb6581a23add416239dfcf7e7f3980c6b913da]
  stable/5.15: [a8a9d753edd7f71e6a2edaa580d8182530b68791]
  stable/5.16: [258b26a34778cde43f228a392e242d3d0420624a]
  stable/5.4: [b0406b5ef4e2c4fb21d9e7d5c36a0453b4279e9b]
  ubuntu/bionic: ['version:4.15.0-169.177']
  ubuntu/focal: ['version:5.4.0-105.119']
ignore:
  debian/stretch-security: f2fs is not supportable
