description: 'usb: gadget: configfs: Fix use-after-free issue with udc_name'
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-39648
- https://git.kernel.org/linus/64e6bbfff52db4bf6785fab9cffab850b2de6870
- https://source.android.com/security/bulletin/pixel/2021-12-01
- https://ubuntu.com/security/notices/USN-5343-1
- https://www.cve.org/CVERecord?id=CVE-2021-39648
comments:
  masami: "4.4 kernel gadget_dev_desc_UDC_show() is bit different from later \nkernel\
    \ versions. However, it looks 4.4 also have same issue."
fixed-by:
  cip/4.19: [83b74059fdf1c4fa6ed261725e6f301552ad23f7]
  cip/4.19-rt: [83b74059fdf1c4fa6ed261725e6f301552ad23f7]
  cip/5.10: [a4b202cba3ab1a7a8b1ca92603931fba5e2032c3]
  cip/5.10-rt: [a4b202cba3ab1a7a8b1ca92603931fba5e2032c3]
  debian/buster-security: ['version:debian/4.19.171-1']
  debian/stretch-security: ['version:debian/4.9.258-1']
  mainline: [64e6bbfff52db4bf6785fab9cffab850b2de6870]
  openela/4.14: [6766064c794afeacc29b21fc09ea4dbe3cae1af3]
  stable/4.14: [6766064c794afeacc29b21fc09ea4dbe3cae1af3]
  stable/4.19: [83b74059fdf1c4fa6ed261725e6f301552ad23f7]
  stable/4.9: [225330e682fa9aaa152287b49dea1ce50fbe0a92]
  stable/5.10: [a4b202cba3ab1a7a8b1ca92603931fba5e2032c3]
  stable/5.4: [bcffe2de9dde74174805d5f56a990353e33b8072]
  ubuntu/bionic: [02892fee14f55672b4d146d88a53d1b317ad5dc1]
  ubuntu/focal: [4f202112942ba9140f610cab516486a493aec3db]
  ubuntu/groovy: [4f2f6cae536ca2cd4789ac06992930a9c6ad6b89]
