description: 'btrfs: abort in rename_exchange if we fail to insert the second ref'
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-47113
- https://git.kernel.org/stable/c/0df50d47d17401f9f140dfbe752a65e5d72f9932
- https://git.kernel.org/stable/c/ff8de2cec65a8c8521faade12a31b39c80e49f5b
- https://git.kernel.org/stable/c/dc09ef3562726cd520c8338c1640872a60187af5
- https://lore.kernel.org/linux-cve-announce/2024031507-CVE-2021-47113-bf29@gregkh/
- https://git.kernel.org/linus/dc09ef3562726cd520c8338c1640872a60187af5
- https://www.cve.org/CVERecord?id=CVE-2021-47113
comments:
  cip/cip-kernel-sec: Introduced commit is not determined.Fixed in v5.13-rc5.
  cip/masami: "This commit log says it's for 4.9+. the btrfs_rename_exchange() is\
    \ not \nfound in the Linux 4.4."
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/5.10: [0df50d47d17401f9f140dfbe752a65e5d72f9932]
  cip/5.10-rt: [0df50d47d17401f9f140dfbe752a65e5d72f9932]
  mainline: [dc09ef3562726cd520c8338c1640872a60187af5]
  stable/5.10: [0df50d47d17401f9f140dfbe752a65e5d72f9932]
  ubuntu/groovy: [ab0799419e626a6aa986639af78c09a49fe5d7e7]
