description: Add exception protection processing for vd in axi_chan_handle_err function
references:
- https://www.cve.org/CVERecord?id=CVE-2023-52899
- https://git.kernel.org/stable/c/f534dc438828cc3f1f8c6895b8bdfbef079521fb
- https://git.kernel.org/stable/c/53dd833fd0a2d8f0118d01ea063a70652689d31e
- https://git.kernel.org/stable/c/20d0a6d17e85a8a816a64fa7d7cae616f1617833
- https://git.kernel.org/stable/c/5054d001ffaf76155637c5e5b922c11016cd6a5d
- https://git.kernel.org/stable/c/51a7ad5b60efac65691729d10745c28fa1016b96
- https://git.kernel.org/stable/c/57054fe516d59d03a7bcf1888e82479ccc244f87
- https://lore.kernel.org/linux-cve-announce/2024082112-CVE-2023-52899-f644@gregkh/
- https://git.kernel.org/linus/57054fe516d59d03a7bcf1888e82479ccc244f87
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v6.2-rc5.
  cip/masami: |-
    Affected file was added by commit 1fe20f1 ("dmaengine: Introduce DW
    AXI DMAC driver") in 4.17-rc1.
  debian/carnil: First introducing commit could not be determined.
introduced-by:
  mainline: [1fe20f1b84548bbcf48b6659ea171cd46618ea3a]
fixed-by:
  cip/4.19: [f534dc438828cc3f1f8c6895b8bdfbef079521fb]
  cip/4.19-rt: [f534dc438828cc3f1f8c6895b8bdfbef079521fb]
  cip/5.10: [20d0a6d17e85a8a816a64fa7d7cae616f1617833]
  cip/5.10-rt: [20d0a6d17e85a8a816a64fa7d7cae616f1617833]
  cip/6.1: [51a7ad5b60efac65691729d10745c28fa1016b96]
  cip/6.1-rt: [51a7ad5b60efac65691729d10745c28fa1016b96]
  mainline: [57054fe516d59d03a7bcf1888e82479ccc244f87]
  stable/4.19: [f534dc438828cc3f1f8c6895b8bdfbef079521fb]
  stable/5.10: [20d0a6d17e85a8a816a64fa7d7cae616f1617833]
  stable/5.15: [5054d001ffaf76155637c5e5b922c11016cd6a5d]
  stable/5.4: [53dd833fd0a2d8f0118d01ea063a70652689d31e]
  stable/6.1: [51a7ad5b60efac65691729d10745c28fa1016b96]
  ubuntu/focal: [4b6fd9c72b753c8ec884f2677fd75de459f301e8]
