description: 'ASoC: ops: Reject out of bounds values in snd_soc_put_volsw_sx()'
references:
- https://www.cve.org/CVERecord?id=CVE-2022-48737
- https://git.kernel.org/linus/4f1e50d6a9cf9c1b8c859d449b5031cacfa8404e
- https://git.kernel.org/stable/c/9e5c40b5706d8aae2cf70bd7e01f0b4575a642d0
- https://git.kernel.org/stable/c/4977491e4b3aad8567f57e2a9992d251410c1db3
- https://git.kernel.org/stable/c/9a12fcbf3c622f9bf6b110a873d62b0cba93972e
- https://git.kernel.org/stable/c/c33402b056de61104b6146dedbe138ca8d7ec62b
- https://git.kernel.org/stable/c/038f8b7caa74d29e020949a43ca368c93f6b29b9
- https://git.kernel.org/stable/c/e8e07c5e25a29e2a6f119fd947f55d7a55eb8a13
- https://git.kernel.org/stable/c/ef6cd9eeb38062a145802b7b56be7ae1090e165e
- https://git.kernel.org/stable/c/4f1e50d6a9cf9c1b8c859d449b5031cacfa8404e
- https://lore.kernel.org/linux-cve-announce/2024062001-CVE-2022-48737-8efb@gregkh/
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v5.17-rc3.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [9a12fcbf3c622f9bf6b110a873d62b0cba93972e]
  cip/4.19-rt: [9a12fcbf3c622f9bf6b110a873d62b0cba93972e]
  cip/4.4: [7a78bde1faa42e0057350378baf518a04b3bae58]
  cip/4.4-rt: [7a78bde1faa42e0057350378baf518a04b3bae58]
  cip/4.4-st: [7a78bde1faa42e0057350378baf518a04b3bae58]
  cip/5.10: [038f8b7caa74d29e020949a43ca368c93f6b29b9]
  cip/5.10-rt: [038f8b7caa74d29e020949a43ca368c93f6b29b9]
  debian/buster-security: ['version:debian/4.19.232-1']
  mainline: [4f1e50d6a9cf9c1b8c859d449b5031cacfa8404e]
  stable/4.19: [9a12fcbf3c622f9bf6b110a873d62b0cba93972e]
  stable/5.10: [038f8b7caa74d29e020949a43ca368c93f6b29b9]
  stable/5.15: [e8e07c5e25a29e2a6f119fd947f55d7a55eb8a13]
  stable/5.4: [c33402b056de61104b6146dedbe138ca8d7ec62b]
  ubuntu/bionic: [e3c7339f1605d81d8a4ea52ffc296d1713818b49]
  ubuntu/focal: [c978f16ce2a5f6c3a27fc551e369aa02d78fd88e]
